#!/bin/bash


case $BLOCK_BUTTON in
	1|3) amixer -q sset Capture toggle ;;
esac

#------------------------------------------------

statusLine=$(amixer get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "off")

if [[ "${status}" = "off" ]]; then
      echo ""
else
      echo ""
fi
