#!/bin/sh


VOL=$(pamixer --get-volume-human | tr -d '%')

if [ "${VOL}" = "muted" ] || [ "${VOL}" = "0" ]; then
    echo ""
else
    echo " ${VOL}%"
fi

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
    1|3) amixer -q sset Master toggle ;;  # right click, mute/unmute
    4) amixer -q sset Master 3%+ unmute ;; # scroll up, increase
    5) amixer -q sset Master 3%- unmute ;; # scroll down, decrease
esac
